import { EEG_DEFAULT_INITIAL_UNRELIABLE_SECONDS } from '../config/eeg';

export const FOCUS_DEFAULT_BASELINE_SECONDS = 15;

export const FOCUS_BASELINE_SECONDS = FOCUS_DEFAULT_BASELINE_SECONDS;

export const FOCUS_BASELINE_MIN_SECONDS = 5;

export const FOCUS_BASELINE_MAX_SECONDS = 300;

export const FOCUS_DEFAULT_DECISION_SECONDS = 15;

export const FOCUS_DECISION_SECONDS = FOCUS_DEFAULT_DECISION_SECONDS;

export const FOCUS_DECISION_MIN_SECONDS = 5;

export const FOCUS_DECISION_MAX_SECONDS = 300;

export const FOCUS_DEFAULT_WARMUP_SECONDS = EEG_DEFAULT_INITIAL_UNRELIABLE_SECONDS;

export const FOCUS_WARMUP_SECONDS = FOCUS_DEFAULT_WARMUP_SECONDS;
