export const EEG_SAMPLE_RATE_HZ = 250;

export const EEG_LIVE_WINDOW_SECONDS = 300;

export const EEG_LIVE_WINDOW_MIN_SECONDS = 30;

export const EEG_LIVE_WINDOW_MAX_SECONDS = 600;

export const EEG_ANALYSIS_HISTORY_SECONDS = EEG_LIVE_WINDOW_MAX_SECONDS;

export const EEG_ANALYSIS_WINDOW_SECONDS = 2;

export const EEG_ANALYSIS_HOP_SECONDS = 0.5;

export const EEG_ENGAGEMENT_EMA_ALPHA = 0.25;

export const EEG_ENGAGEMENT_ALERT_THRESHOLD = 0.5;

export const EEG_INITIAL_UNRELIABLE_SECONDS = 40;

export const EEG_FOCUS_BASELINE_SECONDS = 30;

export const EEG_FOCUS_DECISION_SECONDS = 30;

export const EEG_FOCUS_DECISION_MIN_SECONDS = 5;

export const EEG_FOCUS_DECISION_MAX_SECONDS = 300;

export const EEG_ANALYSIS_WINDOW_SIZE = EEG_SAMPLE_RATE_HZ * EEG_ANALYSIS_WINDOW_SECONDS;

export const EEG_ANALYSIS_HOP_SIZE = EEG_SAMPLE_RATE_HZ * EEG_ANALYSIS_HOP_SECONDS;

export const EEG_DEFAULT_FFT_SIZE = 512;
