export const EEG_SERIAL_BAUD_RATE = 921_600;

export const EEG_SERIAL_RESET_ACK_TIMEOUT_MS = 2_000;

export const EEG_SERIAL_CONFIG_ACK_TIMEOUT_MS = 2_000;

export const EEG_SERIAL_SWITCH_ACK_TIMEOUT_MS = 2_000;

export const EEG_SERIAL_STALLED_TIMEOUT_MS = 2_000;
